FROM i386/ubuntu:latest

COPY ./cprj /cprj

WORKDIR /cprj

RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get install -y clang

RUN gcc -o types_sizes_widths types_sizes_widths.c -Wall -Werror

CMD ["./types_sizes_widths"]